* ox-neuron: A Neuron Zettel Markdown back-end for Org Export Engine

~ox-neuron~ implements a Markdown back-end for Org exporter. The exported Markdown is compatible with the Neuron Zettelkasten note-taking static site generator (https://neuron.zettel.page/). This exporter also handles `org-brain' relationships in notes (https://github.com/Kungsgeten/org-brain).

This code builds on top of the ~ox-hugo~ exporter for the Hugo static site generator (https://ox-hugo.scripter.co) and uses a lot of it's code as-is.

* Status of the work

This is a fully working but first-cut version of the exporter. I am able to generate full static sites from my Org Mode notes, but I know the edge-cases that are not handled. The Issues Tab captures all the pending work and edge-cases, so if you have a doubt, please read through it once.

* How to export your Org Mode notes?

~ox-neuron~ treats any Org Mode heading with the ~:ID~ property as a valid heading for exporting to Neuron. Before starting an export operation, you need to define the variable ~org-neuron-base-dir~ to the file-path where you want to create the Neuron notes. ( Example: ~"/home/vedang/my_neuron_notes/"~ ). You also need to ensure that this path already exists. To create your Neuron static site, you need to create a ~neuron.dhall~ file at this path, with the following contents:
#+begin_example
  { plugins = [ "neuronignore", "links", "uptree", "feed", "dirtree" ]}
#+end_example

You are now ready to export your Org Mode notes to Neuron.

The ~ox-neuron~ backend provides two ways to export data in an org-file:
- Everything under the heading at point.
  + If the point is in a valid Neuron heading, export the content to a Neuron file. The filename derives from the heading ~:ID~. For every valid subheading under this heading, export the content to new Neuron files.
- Everything in the file.
  + Export every valid Neuron heading in the file.
